package at.appfractory.medibot.medibot.alarm

/**
 * Created by Kai Takac on 2019-06-22.
 */
enum class StateMachineResponse {
    INVALID_COMMAND, AWAITING_ALARM_SELECTION, AWAITING_NAME, AWAITING_INTERVAL, CREATION_SUCCESSFUL, STOPPED_SUCCESSFUL, PAUSED_SUCCESSFUL, CONTINUED_SUCCESSFUL, INVALID_ALARM_NAME,

    DELETED_SUCCESSFUL,

    DUPLICATED_ALARM_NAME,

    INVALID_INTERVAL,

    LIST_ALARMS,

    HELP
}